### ISSUE TITLE
osbook_day07aにてmakeコマンドを実行時に'cstdint' file not foundというエラーが発生した

### ISSUE THREAD

**Issue by kebin-lab** [sarisia/mikanos-devcontainer#7]
初めて質問させていただきます。
現在本githubの手順を参考に構築したmikanos-devcontainerを利用して勉強を進めています。

６章（tag:osbook-day6c）までは問題なく進めていたのですが、７章のtag:osbook_07aをcheckoutしたのち、makeコマンドを実行したところ'cstdint' file not foundというエラーが発生しました。
少し調べてみたところ、[参考になりそうなサイト](https://stackoverflow.com/questions/32552249/opencv-cstdint-file-not-found)が見つかりましたので、main.cppにあるincludeの記述方法を以下のように変更して再度makeコマンドを実行してみました。
```main.cpp
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
```

すると、今後は'bits/libc-header-start.h' file not foundというエラーが発生するようになりました。
find /usr -name libc-header-start.hを実行すると以下のようにパスが返ってくることは確認したのですが、解決方法が分からず詰まっている状況です。
```
/usr/include/x86_64-linux-gnu/bits/libc-header-start.h
```

もし解決方法について心当たりがありましたらご教示いただけないでしょうか？

**Comment by sarisia** [comment]
@kebin-lab さん, こんにちは.

こちら, 自分のソースコードでは再現しませんでしたので, いくつか確認したい事項があります:
- checkout しているのは, 公式の mikanos リポジトリでしょうか？ (github.com/uchan-nos/mikanos)
- 実行環境を教えて頂きたいです (Windows? macOS? M1 Mac?)
- これはブートローダのビルドで発生しますか？ それともカーネルのビルドで発生しますか？
  - こちらはわからなければ飛ばしていただいて構いません.

**Comment by kebin-lab** [comment]
早急な返信ありがとうございます。
一つずつ回答させていただきます。
・checkoutしているのは公式のmikanosリポジトリになります
・実行環境はmacOSです。
・~~大変申し訳ありません。勉強不足のためどちらで発生しているエラーか判断できませんでした。~~
⇨おそらくカーネルのビルドで発生していると思われます。
（ご参考までにエラーのスクリーンショットを添付します。）
![スクリーンショット 2021-09-19 18 26 45](https://user-images.githubusercontent.com/54560884/133922377-96137189-d421-4aab-869d-5b1010429fef.jpg)

**Comment by kebin-lab** [comment]
@sarisia さん
私の方で調べたところ、一度vscodeを閉じたことで環境変数が初期化されてしまったことが原因のようでした。
以下のコマンドを叩いたところ上記エラーが出なくなりました。
```
source ~/osbook/devenv/buildenv.sh
```
大変お騒がせして申し訳ありませんでした、、、

**Comment by sarisia** [comment]
ありがとうございます.

スクリーンショットから見るに, カーネルのビルドに見えます.
カーネルビルドでは, `/home/vscode/osbook/devenv/x86_64-elf/include` のヘッダを参照するので,
Docker 及び devcontainer の問題ではないのかな, と思いました.

解決してよかったです！
また何かありましたらご連絡ください！
